# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-349fdf02-640f-453a-a5b9-c91f9816c8c6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-349fdf02-640f-453a-a5b9-c91f9816c8c6".device = "/dev/disk/by-uuid/349fdf02-640f-453a-a5b9-c91f9816c8c6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/104F-33A7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5221701f-290b-4896-ab15-14264b1e5b5d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
