# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-777b3599-698b-4238-a7a6-85b97cd18abd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-777b3599-698b-4238-a7a6-85b97cd18abd".device = "/dev/disk/by-uuid/777b3599-698b-4238-a7a6-85b97cd18abd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7577-F9CA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5e0701c8-00ca-4d08-8f2b-07232ea74946"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
