# Trans flag — blue · pink · white
background #000000
foreground #e8e8e8

color0  #000000
color8  #444444

color1  #F5A9B8
color9  #FFC1D0

color2  #5BCEFA
color10 #8ADFFF

color3  #F5A9B8
color11 #FFC1D0

color4  #5BCEFA
color12 #8ADFFF

color5  #F5A9B8
color13 #FFC1D0

color6  #5BCEFA
color14 #8ADFFF

color7  #e8e8e8
color15 #ffffff
